SET SERVEROUTPUT ON

SET VERIFY OFF  -- QUITA TODA LA MIERDA QUE SALE POR CONSOLA

DECLARE

            -- TE CREA EL MISMO TIPO DE DATO, QUE LA COLUMNA LAST_NAME DE LA TABLA EMPLOYEES
            APELLIDO EMPLOYEES.LAST_NAME%TYPE;
            SALARIO EMPLOYEES.SALARY%TYPE;
            FECHA EMPLOYEES.HIRE_DATE%TYPE;
            DEPARTAMENTO EMPLOYEES.DEPARTMENT_ID%TYPE;
            
            CUANTOS PLS_INTEGER := 0;


BEGIN

            -- LAS VARIABLES DE INTO SON LAS DE ARRIBA, EL RESTO ES LA CONSULTA
            SELECT LAST_NAME, SALARY, HIRE_DATE, DEPARTMENT_ID
            INTO APELLIDO, SALARIO, FECHA, DEPARTAMENTO
            FROM EMPLOYEES
            WHERE EMPLOYEE_ID = &EMPLEADO_ID;  -- AL PONER > CASCA PORQUE DEVUELVE MUCHAS FILAS
           -- WHERE EMPLOYEE_ID= 114;

            DBMS_OUTPUT.PUT_LINE('APELLIDO: '||APELLIDO||CHR(10)||'SALARIO: '||SALARIO||CHR(13)||
            'FECHA: '||FECHA||CHR(10)||'DEPARTAMENTO: '||DEPARTAMENTO);

        
        
            -- CANTIDAD DE EMPLEADOS QUE HAY, EN EL DEPARTAMENTO DE LA VARIABLE O LOS NULOS
            SELECT COUNT(*)
            INTO CUANTOS
            FROM EMPLOYEES
            WHERE DEPARTMENT_ID= DEPARTAMENTO OR DEPARTMENT_ID IS NULL;  -- SI EL EMPLEADO QUE LE PASAS ES NULO LO SACA
            
            DBMS_OUTPUT.PUT_LINE('CANTIDAD DE EMPLEADOS '||CUANTOS);
            
            
            
EXCEPTION
            
            WHEN NO_DATA_FOUND THEN -- ESTE ERROR LO CONTROLAMOS NOSOTROS
                DBMS_OUTPUT.PUT_LINE('EL EMPLEADO TECLEADO NO EXISTE');
            WHEN OTHERS THEN        -- SI NO LO CONTROLAMOS EL ERROR
                DBMS_OUTPUT.PUT_LINE('ERROR EN EL PROGRAMA LLAMADO _PL_SQL_03_.sql : ' ||SQLERRM);

END;
/