SET SERVEROUTPUT ON
SET VERIFY OFF

DECLARE

        -- LO HACEMOS CREANDO TODAS LAS VARIABLES 
        FILA_DEP DEPARTMENTS%ROWTYPE;
         
        -- CREAMOS UNA A UNA LAS VARIABLES
        DPTO_ID DEPARTMENTS.DEPARTMENT_ID%TYPE;
        NAME_ DEPARTMENTS.DEPARTMENT_NAME%TYPE;
        MANA_ID DEPARTMENTS.MANAGER_ID%TYPE;
        LOCAT_ID DEPARTMENTS.LOCAT_ID%TYPE;        

BEGIN

        -- PARA METER POR ALERTA
        FILA_DEP.DEPARTMENT_ID = &CODIGO_DEPARTAMENTO;
        FILA_DEP.DEPARTMENT_NAME= '&NOMBRE_DEPARTAMENTO';
        FILA_DEP.MANAGER_ID= &NUMERO_JEFE;
        FILA_DEP.LOCATION_ID= &NUMBERO_LOCALIDAD;
        INSERT INTO DEPARTMENTS
        VALUES FILA_DEP;
        DBMS_OUTPUT.PUT_LINE('FILA_INSERTADA');
        
        -- ---------------------------------------------------------------------
        -- ---------------------------------------------------------------------
        
        -- PARA  METER POR ALERTA
        DPTO_ID.DEPARTMENT_ID = &CODIGO_DEPART;
        NAME_.DEPARTMENT_NAME= '&NOMBRE_DEPART';
        MANA_ID.MANAGER_ID= &MANAGER_JEFE;
        LOCAT_ID.LOCATION_ID= &LOCATION_ID;
        INSERT INTO DEPARTMENTS
        VALUES (DPTO_ID, NAME_, MANA_ID, LOCAT_ID);
        DBMS_OUTPUT.PUT_LINE('FILA INSERTADA');

EXCEPTION
    
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('ERROR _PL_SQL_16_.sql'||SQLERRM);

END;
/