SET SERVEROUTPUT ON
SET VERIFY OFF


DECLARE



BEGIN

      --   ALTA_DEPARTAMENTO(NULL, NULL, NULL, NULL);
      --      DBMS_OUTPUT.PUT_LINE('FILA INSERTADA');
            
        ALTA_DEPARTAMENTO(280, 'VENTAS', 115, 1700 );
            DBMS_OUTPUT.PUT_LINE('FILA INSERTADA');

EXCEPTION
    
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('ERROR PROGRAMA _PL_SQL_17_.sql '||SQLERRM);

END;
/