

CREATE TABLE AUDITOR_HR
(USUARIO VARCHAR2(45),
MOMENTO TIMESTAMP,
EVENTO VARCHAR2(100)
);
GRANT INSERT, UPDATE ON AUDITOR_HR TO PUBLIC;


SELECT SYSDATE, SYSTIMESTAMP
FROM DUAL;


INSERT INTO JOBS
VALUES('CATABLAS', 'PASDADS', 115, 1500);


UPDATE JOBS 
SET MAX_SALARY= 15000
WHERE JOB_ID= 'IT_PROG';


UPDATE JOBS 
SET MAX_SALARY= 12000
WHERE JOB_ID= 'IT_PROG';

